var kpa = 
[
 {
   "provinsi": "BALI",
   "kabkot": "BULELENG",
   "kecamatan": "GEROKGAK",
   "desa": "SUMBERKIMA",
   "id": 5108012003,
   "organisasi": "Serikat Petani Buleleng (SPB) -Serikat Tani Sumber Hidup",
   "penggunaan": "Pemukiman dan Pertanian",
   "status_tan": "(blank)",
   "pihak_terl": "(blank)",
   "perusahaan": "(blank)",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 114.6105769,
   "lat": -8.157631547
 },
 {
   "provinsi": "BALI",
   "kabkot": "BULELENG",
   "kecamatan": "GEROKGAK",
   "desa": "SUMBERKLAMPOK",
   "id": 5108012001,
   "organisasi": "Serikat Petani Buleleng (SPB) -Serikat Tani Sumber klampok (STS)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "(blank)",
   "pihak_terl": "Pemerintah Daerah",
   "perusahaan": "PT. Margarana, PT. Dharmajati dan Pemprov Bali",
   "tipologi": "HGU Habis Perkebunan Swasta - Aset Pemerintah Daerah",
   "tahapan": "Redistribusi",
   "long": 114.4940472,
   "lat": -8.151013752
 },
 {
   "provinsi": "BALI",
   "kabkot": "GIANYAR",
   "kecamatan": "PAYANGAN",
   "desa": "PUHU",
   "id": 5104072004,
   "organisasi": "Serikat Petani Selasih",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Pemerintah Daerah",
   "perusahaan": "Pemerintah Provinsi Bali",
   "tipologi": "Aset Pemerintah Daerah",
   "tahapan": "Pemetaan",
   "long": 115.2580469,
   "lat": -8.386357556
 },
 {
   "provinsi": "BANTEN",
   "kabkot": "LEBAK",
   "kecamatan": "CIRINTEN",
   "desa": "CIBARANI",
   "id": 3602272010,
   "organisasi": "Rimbawan Muda Indonesia (RMI)",
   "penggunaan": "Perkebunan, Persawahan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 106.2062523,
   "lat": -6.675104786
 },
 {
   "provinsi": "BANTEN",
   "kabkot": "LEBAK",
   "kecamatan": "LEUWIDAMAR",
   "desa": "WANTISARI",
   "id": 3602062010,
   "organisasi": "Pergerakan Petani Banten",
   "penggunaan": "Lahan Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. The Bantam & Preanger Rubber Co. Ltd",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 106.1866659,
   "lat": -6.491679038
 },
 {
   "provinsi": "BENGKULU",
   "kabkot": "BENGKULU UTARA",
   "kecamatan": "HULU PALIK",
   "desa": "BATU ROTO",
   "id": 1703192009,
   "organisasi": "Serikat Tani Bengkulu (STaB)",
   "penggunaan": "kebun dan pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Mangkurajo",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 102.3289818,
   "lat": -3.439234612
 },
 {
   "provinsi": "BENGKULU",
   "kabkot": "BENGKULU UTARA",
   "kecamatan": "HULU PALIK",
   "desa": "PEMATANG BALAM",
   "id": 1703192012,
   "organisasi": "Serikat Tani Bengkulu (STaB)",
   "penggunaan": "kebun dan pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Mangkurajo",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 102.3340372,
   "lat": -3.4202809
 },
 {
   "provinsi": "BENGKULU",
   "kabkot": "BENGKULU UTARA",
   "kecamatan": "KETAHUN",
   "desa": "PASAR KETAHUN",
   "id": 1703122002,
   "organisasi": "Serikat Tani Bengkulu (STaB)",
   "penggunaan": "kebun dan pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Pamor Ganda",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 101.7997083,
   "lat": -3.322648508
 },
 {
   "provinsi": "BENGKULU",
   "kabkot": "BENGKULU UTARA",
   "kecamatan": "PINANG RAYA",
   "desa": "AIR SEBAYUR",
   "id": 1703242001,
   "organisasi": "Serikat Tani Bengkulu (STaB)",
   "penggunaan": "kebun dan pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Sandabi Indah Lestari",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 101.9488244,
   "lat": -3.388077444
 },
 {
   "provinsi": "BENGKULU",
   "kabkot": "BENGKULU UTARA",
   "kecamatan": "PUTRI HIJAU",
   "desa": "KOTA BANI",
   "id": 1703142009,
   "organisasi": "Serikat Tani Bengkulu (STaB)",
   "penggunaan": "kebun dan pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Pamor Ganda",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 101.656579,
   "lat": -3.239366829
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "BATANGHARI",
   "kecamatan": "BAJUBANG",
   "desa": "BUNGKU",
   "id": 1504072001,
   "organisasi": "Serikat Petani Batanghari (SPB)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Hutan Tanaman Industri",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Agronusa Alam Sejahtera\n PT. Wanakasita Nusantara\n PT. Restorasi Ekosistem Indonesia",
   "tipologi": "Konsesi Hutan Konservasi Swasta",
   "tahapan": "Identifikasi",
   "long": 103.3399066,
   "lat": -2.134852642
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "MUARO JAMBI",
   "kecamatan": "KUMPEH ULU",
   "desa": "SUMBER JAYA",
   "id": 1505062017,
   "organisasi": "Serikat Tani Kumpeh",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah HGU Habis Swasta",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. FPIL",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 103.7703279,
   "lat": -1.605367755
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "MUARO JAMBI",
   "kecamatan": "MARO SEBO",
   "desa": "DANAU LAMO",
   "id": 1505042006,
   "organisasi": "Persatuan Petani Jambi (PPJ)",
   "penggunaan": "perkebunan campuran (Akasia dan kelapa sawit",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Wirakarya Sakti",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Identifikasi",
   "long": 103.6471245,
   "lat": -1.418728089
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "TANJUNG JABUNG BARAT",
   "kecamatan": "BETARA",
   "desa": "PEMATANG LUMUT",
   "id": 1506042001,
   "organisasi": "Persatuan Petani Jambi (PPJ)",
   "penggunaan": "perkebunan",
   "status_tan": "Hutan Tanaman Industri",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Wirakarya Sakti",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 103.4165891,
   "lat": -1.090753736
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "TANJUNG JABUNG BARAT",
   "kecamatan": "RENAH MENDALUH",
   "desa": "LAMPISI",
   "id": 1506082004,
   "organisasi": "Pemerintah Desa Lampisi",
   "penggunaan": "Pemukiman, Pertanian dan Perkebunan",
   "status_tan": "Areal Penggunaan Lain",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Salah Subjek Pelepasan Hutan",
   "tahapan": "Pengorganisasian",
   "long": 102.9490954,
   "lat": -1.346152568
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "TANJUNG JABUNG BARAT",
   "kecamatan": "SENYERANG",
   "desa": "SENYERANG",
   "id": 1506131001,
   "organisasi": "Persatuan Petani Jambi (PPJ)",
   "penggunaan": "Pemukiman, Pertanian dan Perkebunan",
   "status_tan": "Hutan Tanaman Industri",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Wirakarya Sakti",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 103.1050113,
   "lat": -0.906589664
 },
 {
   "provinsi": "JAMBI",
   "kabkot": "TANJUNG JABUNG BARAT",
   "kecamatan": "TUNGKAL ULU",
   "desa": "KUALA DASAL",
   "id": 1506012003,
   "organisasi": "Persatuan Petani Jambi (PPJ)",
   "penggunaan": "perkebunan",
   "status_tan": "Hutan Tanaman Industri",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Wirakarya Sakti",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pengorganisasian",
   "long": 103.137889,
   "lat": -1.186710561
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "BANJARANYAR",
   "desa": "BANJARANYAR",
   "id": 3207372002,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 108.5391953,
   "lat": -7.519640559
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "BANJARANYAR",
   "desa": "CIGAYAM",
   "id": 3207372003,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 108.5633236,
   "lat": -7.506439258
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "BANJARANYAR",
   "desa": "CIKASO",
   "id": 3207372007,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 108.5722927,
   "lat": -7.511490981
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "BANJARANYAR",
   "desa": "KALIJAYA",
   "id": 3207372005,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 108.5349824,
   "lat": -7.55386511
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "BANJARANYAR",
   "desa": "PASAWAHAN",
   "id": 3207372001,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 108.5776316,
   "lat": -7.547680719
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "CIHAURBEUTI",
   "desa": "SUKAMAJU",
   "id": 3207062004,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 108.2267969,
   "lat": -7.238619888
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "CIPAKU",
   "desa": "MUKTISARI",
   "id": 3207112007,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Maloya",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 108.3676404,
   "lat": -7.261975275
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "SUKADANA",
   "desa": "MARGAHARJA",
   "id": 3207142003,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.4546245,
   "lat": -7.250093515
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "TAMBAKSARI",
   "desa": "KASO",
   "id": 3207162003,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 108.5637582,
   "lat": -7.242928564
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIAMIS",
   "kecamatan": "TAMBAKSARI",
   "desa": "SUKASARI",
   "id": 3207162005,
   "organisasi": "Serikat Petani Pasundan (SPP Ciamis)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Jonggol Asri",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 108.5344887,
   "lat": -7.208423105
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "CIANJUR",
   "kecamatan": "CAMPAKA",
   "desa": "CIMENTENG",
   "id": 3203152002,
   "organisasi": "Paguyuban Petani Cianjur (PPC)",
   "penggunaan": "pemukiman, perkebunan dan pesawahan",
   "status_tan": "Tanah Terlantar HGU Swasta",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Harjasari",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 107.054881,
   "lat": -6.972933307
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "CIBALONG",
   "desa": "KARYASARI",
   "id": 3205292001,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara VIII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 107.7945334,
   "lat": -7.666072078
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "CIBALONG",
   "desa": "SAGARA",
   "id": 3205292005,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara VIII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 107.8563999,
   "lat": -7.655242019
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "CIKAJANG",
   "desa": "MARGAMULYA",
   "id": 3205222010,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "Pertanian dan Perkebunan",
   "status_tan": "(blank)",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 107.7484233,
   "lat": -7.358307384
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "CILAWU",
   "desa": "DANGIANG",
   "id": 3205192012,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman, sekolah, rumah ibadah, jalan desa yang dibangun swadaya oleh masyarakat",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara VIII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 107.8870316,
   "lat": -7.293310099
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "CILAWU",
   "desa": "MEKARMUKTI",
   "id": 3205192008,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman, sekolah, rumah ibadah, jalan desa yang dibangun swadaya oleh masyarakat",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara VIII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 107.874735,
   "lat": -7.288301877
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "CILAWU",
   "desa": "SUKAMUKTI",
   "id": 3205192002,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman, sekolah, rumah ibadah, jalan desa yang dibangun swadaya oleh masyarakat",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara VIII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 107.8788533,
   "lat": -7.290691339
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "KADUNGORA",
   "desa": "GANDAMEKAR",
   "id": 3205102002,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 107.9026631,
   "lat": -7.064952334
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "KADUNGORA",
   "desa": "MEKARBAKTI",
   "id": 3205102007,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 107.912363,
   "lat": -7.064093518
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "GARUT",
   "kecamatan": "PASIRWANGI",
   "desa": "SARIMUKTI",
   "id": 3205082011,
   "organisasi": "Serikat Petani Pasundan Garut (SPP Garut)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 107.7244343,
   "lat": -7.231194181
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "INDRAMAYU",
   "kecamatan": "CIKEDUNG",
   "desa": "LOYANG",
   "id": 3212042003,
   "organisasi": "Serikat Tani Indramayu (STI)",
   "penggunaan": "Pertanian dan pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.1437966,
   "lat": -6.538791305
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "INDRAMAYU",
   "kecamatan": "GANTAR",
   "desa": "SANCA",
   "id": 3212252002,
   "organisasi": "Serikat Tani Indramayu (STI)",
   "penggunaan": "Pertanian dan pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 107.8746407,
   "lat": -6.575594607
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "INDRAMAYU",
   "kecamatan": "KROYA",
   "desa": "KROYA",
   "id": 3212022002,
   "organisasi": "Serikat Tani Indramayu (STI)",
   "penggunaan": "Pertanian dan pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.059449,
   "lat": -6.527499822
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "INDRAMAYU",
   "kecamatan": "KROYA",
   "desa": "TANJUNGKERTA",
   "id": 3212022001,
   "organisasi": "Serikat Tani Indramayu (STI)",
   "penggunaan": "Pertanian dan pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 108.0281612,
   "lat": -6.508740424
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "MAJALENGKA",
   "kecamatan": "DAWUAN",
   "desa": "SALAWANA",
   "id": 3210122013,
   "organisasi": "Serikat Petani Majalengka (SPM)",
   "penggunaan": "Daratan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Tentara Nasional Indonesia",
   "perusahaan": "Lanud Sugiri Sukani",
   "tipologi": "Aset TNI",
   "tahapan": "Pemetaan",
   "long": 108.2286522,
   "lat": -6.695730453
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "MAJALENGKA",
   "kecamatan": "KERTAJATI",
   "desa": "MEKARMULYA",
   "id": 3210142012,
   "organisasi": "Serikat Petani Majalengka (SPM)",
   "penggunaan": "Persawahan, Perkebunan",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.1125122,
   "lat": -6.597134131
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "MAJALENGKA",
   "kecamatan": "KERTAJATI",
   "desa": "SUKAMULYA",
   "id": 3210142009,
   "organisasi": "Serikat Petani Majalengka (SPM)",
   "penggunaan": "Persawahan, Perkebunan",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Objek Pembangunan Bandara",
   "tahapan": "Redistribusi",
   "long": 108.1423621,
   "lat": -6.636678332
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "MAJALENGKA",
   "kecamatan": "LIGUNG",
   "desa": "CIBOGOR",
   "id": 3210162001,
   "organisasi": "Serikat Petani Majalengka (SPM)",
   "penggunaan": "Daratan",
   "status_tan": "1084 Jiwa (pemilik Pemukiman),390 jiwa Pemilik Sawa",
   "pihak_terl": "Tentara Nasional Indonesia",
   "perusahaan": "Lanud Sugiri Sukani",
   "tipologi": "Aset TNI",
   "tahapan": "Identifikasi",
   "long": 108.2312603,
   "lat": -6.685270505
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "MAJALENGKA",
   "kecamatan": "LIGUNG",
   "desa": "KERTASARI",
   "id": 3210162012,
   "organisasi": "Serikat Petani Majalengka (SPM)",
   "penggunaan": "Daratan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Tentara Nasional Indonesia",
   "perusahaan": "Lanud Sugiri Sukani",
   "tipologi": "Aset TNI",
   "tahapan": "Pengorganisasian",
   "long": 108.2350423,
   "lat": -6.6747377
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "CIGUGUR",
   "desa": "HARUMANDALA",
   "id": 3218042007,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.3644931,
   "lat": -7.563972187
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "CIGUGUR",
   "desa": "KERTAJAYA",
   "id": 3218042004,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman, sawah, sarana umum, sarana ibadah, pendidikan dan kebun karet rakyat",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.372813,
   "lat": -7.639138072
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "CIGUGUR",
   "desa": "PAGERBUMI",
   "id": 3218042003,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman, sawah, sarana umum, sarana ibadah, pendidikan dan kebun rakyat",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.3751364,
   "lat": -7.596623191
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "KALIPUCANG",
   "desa": "PAMOTAN",
   "id": 3218082004,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.7766376,
   "lat": -7.671829409
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "LANGKAPLANCAR",
   "desa": "BANGUNKARYA",
   "id": 3218052011,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.4979535,
   "lat": -7.595612489
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "LANGKAPLANCAR",
   "desa": "JADIKARYA",
   "id": 3218052009,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.4770393,
   "lat": -7.566281445
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "LANGKAPLANCAR",
   "desa": "JADIMULYA",
   "id": 3218052008,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.480483,
   "lat": -7.622743158
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "PANGANDARAN",
   "desa": "PURBAHAYU",
   "id": 3218092003,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.6490604,
   "lat": -7.656079506
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "PARIGI",
   "desa": "SELASARI",
   "id": 3218012006,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.5299801,
   "lat": -7.605624032
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "PANGANDARAN",
   "kecamatan": "SIDAMULIH",
   "desa": "KERSARATU",
   "id": 3218102006,
   "organisasi": "Serikat Petani Pasundan (SPP Pangandaran)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.5823171,
   "lat": -7.609534389
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIGALONTANG",
   "desa": "TANJUNGKARANG",
   "id": 3206272015,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman, sawah, sarana umum, sarana ibadah, pendidikan dan kebun rakyat",
   "status_tan": "Hutan Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 107.9701256,
   "lat": -7.322722466
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIKALONG",
   "desa": "CIKADU",
   "id": 3206032007,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman, sawah, sarana umum, sarana ibadah, pendidikan dan kebun rakyat",
   "status_tan": "Hutan Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.2256088,
   "lat": -7.769620851
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIKALONG",
   "desa": "MANDALAJAYA",
   "id": 3206032008,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman, sawah, sarana umum, sarana ibadah, pendidikan dan kebun rakyat",
   "status_tan": "Hutan Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.1837635,
   "lat": -7.779504659
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIKATOMAS",
   "desa": "SINDANGASIH",
   "id": 3206052007,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pertanian, pemukiman,sekolah,Rumah Ibadah,Pesantren",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara VIII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 108.3231237,
   "lat": -7.566741725
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIPATUJAH",
   "desa": "CIANDUM",
   "id": 3206012012,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT KPP Genteng",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 107.9990781,
   "lat": -7.716050937
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIPATUJAH",
   "desa": "CIHERAS",
   "id": 3206012001,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "Pemukiman,sawah,sekolah,sarana ibadah, pendidikan, kebun rakyat",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 107.9456451,
   "lat": -7.720519656
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "CIPATUJAH",
   "desa": "NAGROG",
   "id": 3206012007,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "(blank)",
   "status_tan": "Hutan Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.0167025,
   "lat": -7.66073087
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "KARANGNUNGGAL",
   "desa": "KARANGNUNGGAL",
   "id": 3206022004,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman,pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Pernas",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 108.1379766,
   "lat": -7.645964974
 },
 {
   "provinsi": "JAWA BARAT",
   "kabkot": "TASIKMALAYA",
   "kecamatan": "TARAJU",
   "desa": "BANYUASIH",
   "id": 3206132006,
   "organisasi": "Serikat Petani Pasundan Tasikmalaya (SPP Tasikmalaya)",
   "penggunaan": "pemukiman, sawah, sarana umum, sarana ibadah, pendidikan dan kebun kopi rakyat",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 107.9607772,
   "lat": -7.454292125
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BANYUMAS",
   "kecamatan": "AJIBARANG",
   "desa": "DARMAKRADENAN",
   "id": 3302142001,
   "organisasi": "Serikat Tani Amanat Penderitaan Rakyat (STAM AMPERA)",
   "penggunaan": "perkebunan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rumpun Sari Antan",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 109.0337703,
   "lat": -7.421228465
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "BANDAR",
   "desa": "TUMBREP",
   "id": 3325022013,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "perkebunan dan pesawahan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perusahaan Perkebunan Tratak",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 109.8137463,
   "lat": -7.05806201
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "BLADO",
   "desa": "BAWANG",
   "id": 3325032011,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Perindustrian Perdagangan\n PT. Pagilaran Unit Produksi Sidoharjo",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 109.82777,
   "lat": -7.08572512
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "BLADO",
   "desa": "BISMO",
   "id": 3325032005,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Perindustrian Perdagangan\n PT. Pagilaran Unit Produksi Sidoharjo",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 109.8359116,
   "lat": -7.12682078
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "BLADO",
   "desa": "GONDANG",
   "id": 3325032004,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Perindustrian Perdagangan\n PT. Pagilaran Unit Produksi Sidoharjo",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 109.8288758,
   "lat": -7.107045937
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "BLADO",
   "desa": "KALISARI",
   "id": 3325032007,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Perindustrian Perdagangan\n PT. Pagilaran Unit Produksi Sidoharjo",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 109.859669,
   "lat": -7.095539522
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "SUBAH",
   "desa": "GONDANG",
   "id": 3325092023,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 109.868195,
   "lat": -6.935383022
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "SUBAH",
   "desa": "KURIPAN",
   "id": 3325092024,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 109.891571,
   "lat": -6.928672742
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BATANG",
   "kecamatan": "SUBAH",
   "desa": "SUBAH",
   "id": 3325092011,
   "organisasi": "Forum Perjuangan Petani Batang (FPPB)",
   "penggunaan": "Persawahan",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 109.8713077,
   "lat": -6.972655895
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "BOYOLALI",
   "kecamatan": "KEMUSU",
   "desa": "BAWU",
   "id": 3309172005,
   "organisasi": "Serikat Paguyuban Petani Qaryah Thayyibah (SPPQT)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Hutan Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 110.7349892,
   "lat": -7.31152719
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "BANTARSARI",
   "desa": "BANTARSARI",
   "id": 3301202002,
   "organisasi": "Lembaga Penelitian Pengembangan Sumberdaya dan Lingkungan Hidup (LPPSLH)",
   "penggunaan": "Pertanian (Sawah)",
   "status_tan": "Hak Garap",
   "pihak_terl": "Pemerintah Daerah",
   "perusahaan": "(blank)",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.8661019,
   "lat": -7.59150255
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "BANTARSARI",
   "desa": "CITEMBONG",
   "id": 3301202005,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.9453385,
   "lat": -7.481568818
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIMANGGU",
   "desa": "KARANGREJA",
   "id": 3301132013,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sendimentasi",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara IX",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 108.793837,
   "lat": -7.354913571
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIPARI",
   "desa": "CISURU",
   "id": 3301182004,
   "organisasi": "PP. SeTAM",
   "penggunaan": "Sawah, pekarangan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rumpun Sari Antan",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 108.7331778,
   "lat": -7.38506742
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIPARI",
   "desa": "KARANGREJA",
   "id": 3301182010,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sendimentasi",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rumpun Sari Antan",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 108.807308,
   "lat": -7.413500207
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIPARI",
   "desa": "KUTASARI",
   "id": 3301182009,
   "organisasi": "PP. SeTAM",
   "penggunaan": "Sawah",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rumpun Sari Antan",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 108.8301775,
   "lat": -7.390791613
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIPARI",
   "desa": "MEKARSARI",
   "id": 3301182008,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Perumahan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rumpun Sari Antan",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 108.74408,
   "lat": -7.394496442
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIPARI",
   "desa": "MULYADADI",
   "id": 3301182007,
   "organisasi": "PP. SeTAM",
   "penggunaan": "Sawah, pekarangan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rumpun Sari Antan",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 108.7481468,
   "lat": -7.42737551
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "CIPARI",
   "desa": "SIDASARI",
   "id": 3301182011,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sendimentasi",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Ciseru",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 108.7790086,
   "lat": -7.385230135
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "DAYEUHLUHUR",
   "desa": "DAYEUHLUHUR",
   "id": 3301162004,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sendimentasi",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara IX",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 108.61561,
   "lat": -7.258714473
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "GANDRUNGMANGU",
   "desa": "CISUMUR",
   "id": 3301102003,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.823211,
   "lat": -7.53490621
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "GANDRUNGMANGU",
   "desa": "SIDAURIP",
   "id": 3301102008,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 108.8346932,
   "lat": -7.570349876
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "JERUKLEGI",
   "desa": "SAWANGAN",
   "id": 3301082011,
   "organisasi": "PP. SeTAM",
   "penggunaan": "Pekarangan dan sawah",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Adiwiyata Panca Arga",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 108.9917957,
   "lat": -7.586748541
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "KAWUNGANTEN",
   "desa": "BABAKAN",
   "id": 3301092014,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.9374282,
   "lat": -7.662035841
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "KAWUNGANTEN",
   "desa": "BRINGKENG",
   "id": 3301092002,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.9151291,
   "lat": -7.634028418
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "KAWUNGANTEN",
   "desa": "GRUGU",
   "id": 3301092001,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 108.9084797,
   "lat": -7.650851968
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "PATIMUAN",
   "desa": "BULUPAYUNG",
   "id": 3301192006,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.8043282,
   "lat": -7.592381616
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "PATIMUAN",
   "desa": "CIMRUTU",
   "id": 3301192007,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 108.800654,
   "lat": -7.625150931
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "PATIMUAN",
   "desa": "CINYAWANG",
   "id": 3301192005,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman",
   "status_tan": "Tanah bekas HPL",
   "pihak_terl": "Pemerintah Daerah",
   "perusahaan": "Dinas Perairan",
   "tipologi": "Aset Pemerintah Daerah",
   "tahapan": "Identifikasi",
   "long": 108.7666729,
   "lat": -7.574436251
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "PATIMUAN",
   "desa": "RAWAAPU",
   "id": 3301192002,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Sedimentasi",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 108.7773364,
   "lat": -7.640175197
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "CILACAP",
   "kecamatan": "WANAREJA",
   "desa": "BANTAR",
   "id": 3301152002,
   "organisasi": "Serikat Tani Mandiri (SETAM)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara IX",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 108.7104302,
   "lat": -7.366395657
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "KENDAL",
   "kecamatan": "PAGERUYUNG",
   "desa": "SUROKONTO KULON",
   "id": 3324022013,
   "organisasi": "Lembaga Bantuan Hukum Semarang (LBH SEMARANG)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Sumur Pitu Wringinsari, PT Semen Indonesia, Perhutani & Pemda",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 110.0352053,
   "lat": -7.011220836
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "KENDAL",
   "kecamatan": "PAGERUYUNG",
   "desa": "SUROKONTO WETAN",
   "id": 3324022010,
   "organisasi": "Lembaga Bantuan Hukum Semarang (LBH SEMARANG)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT Sumur Pitu Wringinsari, PT Semen Indonesia, Perhutani & Pemda",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 110.0497859,
   "lat": -7.019862157
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "KENDAL",
   "kecamatan": "SINGOROJO",
   "desa": "BANYURINGIN",
   "id": 3324052005,
   "organisasi": "Lembaga Bantuan Hukum Semarang (LBH SEMARANG)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Pekebunan Nusantara IX",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 110.2098164,
   "lat": -7.114082214
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "KENDAL",
   "kecamatan": "SINGOROJO",
   "desa": "KALIREJO",
   "id": 3324052010,
   "organisasi": "Forum Petani Persatuan Kendal (FPPK)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 110.2264958,
   "lat": -7.065174906
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "MAGELANG",
   "kecamatan": "SALAMAN",
   "desa": "NGARGORETNO",
   "id": 3308012001,
   "organisasi": "PP. SeTAM",
   "penggunaan": "(blank)",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "(blank)",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 110.1488796,
   "lat": -7.636002044
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "PEMALANG",
   "kecamatan": "BELIK",
   "desa": "SIKASUR",
   "id": 3327032011,
   "organisasi": "Sarekat Pengorganisasian Rakyat (SPR)",
   "penggunaan": "perkebunan, pesawahan, galian C, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Kencana Sikasur",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 109.3091858,
   "lat": -7.118001341
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "PEMALANG",
   "kecamatan": "PETARUKAN",
   "desa": "KLAREYAN",
   "id": 3327102018,
   "organisasi": "Serikat Tani Independen Pemalang (STIP)",
   "penggunaan": "tambak, kebun dan sawah",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Mackenzie",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 109.474575,
   "lat": -6.848553672
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "SEMARANG",
   "kecamatan": "GETASAN",
   "desa": "BATUR",
   "id": 3322012002,
   "organisasi": "Serikat Paguyuban Petani Qaryah Thayyibah (SPPQT)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Hutan Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Identifikasi",
   "long": 110.436193,
   "lat": -7.403497407
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "SEMARANG",
   "kecamatan": "PRINGAPUS",
   "desa": "WONOREJO",
   "id": 3322152006,
   "organisasi": "Serikat Paguyuban Petani Qaryah Thayyibah (SPPQT)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 110.4924331,
   "lat": -7.160050313
 },
 {
   "provinsi": "JAWA TENGAH",
   "kabkot": "SRAGEN",
   "kecamatan": "SAMBIREJO",
   "desa": "JETIS",
   "id": 3314052003,
   "organisasi": "Forum Peduli Kebenaran dan Keadilan Sambirejo (FPKKS)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara IX Kerjoarum",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 111.1090456,
   "lat": -7.519439192
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "BANYUWANGI",
   "kecamatan": "TEGALDLIMO",
   "desa": "KEDUNGASRI",
   "id": 3510042003,
   "organisasi": "Pemerintah Desa Kedungasri",
   "penggunaan": "perumahan, peribadahan dan persawahan",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pengorganisasian",
   "long": 114.3414163,
   "lat": -8.534861476
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "BLITAR",
   "kecamatan": "DOKO",
   "desa": "SIDOREJO",
   "id": 3505182008,
   "organisasi": "Paguyuban Petani Aryo Blitar (PPAB) dan Sitas Desa",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Gapri",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 112.3919417,
   "lat": -8.061803487
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "BLITAR",
   "kecamatan": "GANDUSARI",
   "desa": "SUMBERAGUNG",
   "id": 3505152001,
   "organisasi": "Paguyuban Petani Aryo Blitar (PPAB) dan Sitas Desa",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rotorejo Kruwuk",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 112.2714911,
   "lat": -8.050155253
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "BLITAR",
   "kecamatan": "WATES",
   "desa": "RINGINREJO",
   "id": 3505202004,
   "organisasi": "Paguyuban Petani Aryo Blitar (PPAB) dan Sitas Desa",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Gondang Tapen/Perthutani/PT Semen Holcim (Tukar Guling)",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 112.3337875,
   "lat": -8.304483258
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "AJUNG",
   "desa": "MANGARAN",
   "id": 3509172002,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "persawahan,pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 113.6221806,
   "lat": -8.26436934
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "AMBULU",
   "desa": "SABRANG",
   "id": 3509122002,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 113.614795,
   "lat": -8.413432576
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "MUMBULSARI",
   "desa": "MUMBULSARI",
   "id": 3509232004,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "persawahan,pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 113.7327319,
   "lat": -8.253708513
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "PANTI",
   "desa": "SUCI",
   "id": 3509142005,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "perkebunan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 113.6185667,
   "lat": -8.061272415
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "RAMBIPUJI",
   "desa": "NOGOSARI",
   "id": 3509132001,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "perkebunan",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 113.5865988,
   "lat": -8.261126877
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "SILO",
   "desa": "MULYOREJO",
   "id": 3509302006,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 113.8610922,
   "lat": -8.327086517
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "TEMPUREJO",
   "desa": "CURAHNONGKO",
   "id": 3509182006,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 113.6803651,
   "lat": -8.420471758
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "JEMBER",
   "kecamatan": "TEMPUREJO",
   "desa": "CURAHTAKIR",
   "id": 3509182007,
   "organisasi": "Serikat Tani Independen (SEKTI)",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 113.7462472,
   "lat": -8.332638194
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "KEDIRI",
   "kecamatan": "PLOSOKLATEN",
   "desa": "SEPAWON",
   "id": 3506092015,
   "organisasi": "Serikat Rakyat Kediri Berdaulat (SRKB)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 112.2337012,
   "lat": -7.904122422
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "KEDIRI",
   "kecamatan": "PUNCU",
   "desa": "SATAK",
   "id": 3506082008,
   "organisasi": "Serikat Rakyat Kediri Berdaulat (SRKB)",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XII",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 112.2422299,
   "lat": -7.872888718
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "LUMAJANG",
   "kecamatan": "PASRUJAMBE",
   "desa": "PASRUJAMBE",
   "id": 3508112001,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 112.9716227,
   "lat": -8.086325467
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "LUMAJANG",
   "kecamatan": "PRONOJIWO",
   "desa": "SUPITURANG",
   "id": 3508022006,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 112.9841486,
   "lat": -8.157579303
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "MOJOKERTO",
   "kecamatan": "PACET",
   "desa": "PACET",
   "id": 3516032005,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Negara",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Pemetaan",
   "long": 112.5398478,
   "lat": -7.671613977
 },
 {
   "provinsi": "JAWA TIMUR",
   "kabkot": "TULUNGAGUNG",
   "kecamatan": "GONDANG",
   "desa": "SIDEM",
   "id": 3504092014,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Pemukiman, Pertanian",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Kehutanan Negara",
   "perusahaan": "Perum Perhutani",
   "tipologi": "Klaim Hutan Perhutani",
   "tahapan": "Redistribusi",
   "long": 111.7988467,
   "lat": -8.056200123
 },
 {
   "provinsi": "KALIMANTAN BARAT",
   "kabkot": "SANGGAU",
   "kecamatan": "NOYAN",
   "desa": "SUNGAI DANGIN",
   "id": 6103032004,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Hutan Lindung",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Lindung",
   "tahapan": "Redistribusi",
   "long": 110.6075967,
   "lat": 0.705268225
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "LAMPUNG SELATAN",
   "kecamatan": "KETAPANG",
   "desa": "KARANG SARI",
   "id": 1801142003,
   "organisasi": "Forum Masyarakat Register (FORMASTER)",
   "penggunaan": "Pemukiman dan Pertanian",
   "status_tan": "Hutan Produksi",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Produksi",
   "tahapan": "Pengorganisasian",
   "long": 105.7247287,
   "lat": -5.74389564
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "LAMPUNG SELATAN",
   "kecamatan": "KETAPANG",
   "desa": "KEMUKUS",
   "id": 1801142014,
   "organisasi": "Forum Masyarakat Register (FORMASTER)",
   "penggunaan": "Pemukiman dan Pertanian",
   "status_tan": "Hutan Produksi",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Produksi",
   "tahapan": "Pengorganisasian",
   "long": 105.7499055,
   "lat": -5.707686064
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "LAMPUNG SELATAN",
   "kecamatan": "KETAPANG",
   "desa": "LEBUNG NALA",
   "id": 1801142015,
   "organisasi": "Forum Masyarakat Register (FORMASTER)",
   "penggunaan": "Pemukiman dan Pertanian",
   "status_tan": "Hutan Produksi",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Produksi",
   "tahapan": "Pengorganisasian",
   "long": 105.7680592,
   "lat": -5.691408017
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "LAMPUNG SELATAN",
   "kecamatan": "PALAS",
   "desa": "PEMATANG BARU",
   "id": 1801102016,
   "organisasi": "Forum Masyarakat Register (FORMASTER)",
   "penggunaan": "Pemukiman dan Pertanian",
   "status_tan": "Hutan Produksi",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 105.6949235,
   "lat": -5.661493356
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "LAMPUNG SELATAN",
   "kecamatan": "PENENGAHAN",
   "desa": "GANDRI",
   "id": 1801092026,
   "organisasi": "Forum Masyarakat Register (FORMASTER)",
   "penggunaan": "penmukiman dan pertanian",
   "status_tan": "Hutan Produksi",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Produksi",
   "tahapan": "Pengorganisasian",
   "long": 105.7277629,
   "lat": -5.703707943
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "TULANG BAWANG",
   "kecamatan": "BANJAR MARGO",
   "desa": "AGUNG JAYA",
   "id": 1805202010,
   "organisasi": "Serikat Tani Korban Penggusuran Pt. Bnil (STKGB)",
   "penggunaan": "ladang",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Bangun Nusa Indah Lampung",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 105.2407082,
   "lat": -4.216573729
 },
 {
   "provinsi": "LAMPUNG",
   "kabkot": "TULANG BAWANG",
   "kecamatan": "BANJAR MARGO",
   "desa": "BUJUK AGUNG",
   "id": 1805202001,
   "organisasi": "Serikat Tani Korban Penggusuran Pt. Bnil (STKGB)",
   "penggunaan": "ladang",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Bangun Nusa Indah Lampung",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 105.2360265,
   "lat": -4.201122037
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU TIMUR",
   "kecamatan": "ANGKONA",
   "desa": "MANTADULU",
   "id": 7324052005,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Dijadikan Kebun Sawit",
   "status_tan": "Tanah Hak Milik Transmigrasi",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 120.9354537,
   "lat": -2.451022581
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU TIMUR",
   "kecamatan": "MALILI",
   "desa": "HARAPAN",
   "id": 7324042001,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Perkebunan dan pemukiman",
   "status_tan": "Tanah Hak Milik Transmigrasi",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 121.0990011,
   "lat": -2.749569298
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU TIMUR",
   "kecamatan": "NUHA",
   "desa": "MATANO",
   "id": 7324022005,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Persawahan,pemukiman,peternakan,hutan,danau,perkebunan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Vale Indonesia",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 121.1601051,
   "lat": -2.404970707
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU TIMUR",
   "kecamatan": "NUHA",
   "desa": "NUHA",
   "id": 7324022001,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Persawahan,pemukiman,peternakan,hutan,danau,perkebunan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Vale Indonesia",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 121.4029604,
   "lat": -2.441055195
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "MAPPEDECENG",
   "desa": "URASO",
   "id": 7322102005,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Pemukiman,pertanian/perkebunan dan peternakan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 120.4417627,
   "lat": -2.486854142
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "RAMPI",
   "desa": "DODOLO",
   "id": 7322092004,
   "organisasi": "Perkumpulan Wallacea Palopo, SLPP Tokalekaju",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan, Fasum",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Tambang Swasta",
   "perusahaan": "PT. Kalla Arebama\n PT. Citra Palu Minerals",
   "tipologi": "Konsesi Tambang Emas",
   "tahapan": "Pengorganisasian",
   "long": 120.2348065,
   "lat": -2.145401046
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "RAMPI",
   "desa": "LEBONI",
   "id": 7322092003,
   "organisasi": "Perkumpulan Wallacea Palopo, SLPP Tokalekaju",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan, Fasum",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Tambang Swasta",
   "perusahaan": "PT. Kalla Arebama\n PT. Citra Palu Minerals",
   "tipologi": "Konsesi Tambang Emas",
   "tahapan": "Pengorganisasian",
   "long": 120.411142,
   "lat": -2.117331539
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "RAMPI",
   "desa": "ONONDOWA",
   "id": 7322092002,
   "organisasi": "Perkumpulan Wallacea Palopo, SLPP Tokalekaju",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan, Fasum",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Tambang Swasta",
   "perusahaan": "PT. Kalla Arebama\n PT. Citra Palu Minerals",
   "tipologi": "Konsesi Tambang Emas",
   "tahapan": "Pemetaan",
   "long": 120.2996459,
   "lat": -2.093442175
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "RAMPI",
   "desa": "RAMPI",
   "id": 7322092001,
   "organisasi": "Perkumpulan Wallacea Palopo, SLPP Tokalekaju",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan, Fasum",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Tambang Swasta",
   "perusahaan": "PT. Kalla Arebama\n PT. Citra Palu Minerals",
   "tipologi": "Konsesi Tambang Emas",
   "tahapan": "Pemetaan",
   "long": 120.1950068,
   "lat": -2.144056602
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "RAMPI",
   "desa": "SULAKU",
   "id": 7322092005,
   "organisasi": "Perkumpulan Wallacea Palopo, SLPP Tokalekaju",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan, Fasum",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Tambang Swasta",
   "perusahaan": "PT. Kalla Arebama\n PT. Citra Palu Minerals",
   "tipologi": "Konsesi Tambang Emas",
   "tahapan": "Redistribusi",
   "long": 120.3118692,
   "lat": -2.144182624
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "RAMPI",
   "desa": "TEDEBOE",
   "id": 7322092006,
   "organisasi": "Perkumpulan Wallacea Palopo, SLPP Tokalekaju",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan, Fasum",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Tambang Swasta",
   "perusahaan": "PT. Kalla Arebama\n PT. Citra Palu Minerals",
   "tipologi": "Konsesi Tambang Emas",
   "tahapan": "Redistribusi",
   "long": 120.1244817,
   "lat": -2.147544131
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "SEKO",
   "desa": "LODANG",
   "id": 7322072009,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Pemukiman,pertanian/perkebunan, persawahan, Kolam Ikan/empang dan peternakan/pengembalaan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Seko Fajar Plantation",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 119.987311,
   "lat": -2.385588293
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "SEKO",
   "desa": "MARANTE",
   "id": 7322072012,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Pemukiman,pertanian/perkebunan, persawahan, Kolam Ikan/empang dan peternakan/pengembalaan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Seko Fajar Plantation",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 119.937467,
   "lat": -2.093927512
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "SEKO",
   "desa": "PADANG BALUA",
   "id": 7322072004,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Pemukiman,pertanian/perkebunan, persawahan, Kolam Ikan/empang dan peternakan/pengembalaan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Seko Fajar Plantation",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 119.9141215,
   "lat": -2.255611766
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "SEKO",
   "desa": "PADANG RAYA",
   "id": 7322072005,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Pemukiman,pertanian/perkebunan, persawahan, Kolam Ikan/empang dan peternakan/pengembalaan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Seko Fajar Plantation",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 119.9178186,
   "lat": -2.294650046
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "LUWU UTARA",
   "kecamatan": "SEKO",
   "desa": "TALOTO",
   "id": 7322072010,
   "organisasi": "Perkumpulan WALLACEA Palopo",
   "penggunaan": "Pemukiman,pertanian/perkebunan, persawahan, Kolam Ikan/empang dan peternakan/pengembalaan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Seko Fajar Plantation",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Redistribusi",
   "long": 120.0312077,
   "lat": -2.205340292
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "WAJO",
   "kecamatan": "KEERA",
   "desa": "AWO",
   "id": 7313142008,
   "organisasi": "Forum Rakyat Bersatu (FRB) Keera.",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 120.2092911,
   "lat": -3.778232329
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "WAJO",
   "kecamatan": "KEERA",
   "desa": "AWOTA",
   "id": 7313142002,
   "organisasi": "Forum Rakyat Bersatu (FRB) Keera.",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 120.2706676,
   "lat": -3.755998863
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "WAJO",
   "kecamatan": "KEERA",
   "desa": "CIROMANIE",
   "id": 7313142009,
   "organisasi": "Forum Rakyat Bersatu (FRB) Keera.",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 120.2913754,
   "lat": -3.81506967
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "WAJO",
   "kecamatan": "KEERA",
   "desa": "INRELLO",
   "id": 7313142006,
   "organisasi": "Forum Rakyat Bersatu (FRB) Keera.",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 120.3010118,
   "lat": -3.859014863
 },
 {
   "provinsi": "SULAWESI SELATAN",
   "kabkot": "WAJO",
   "kecamatan": "KEERA",
   "desa": "LABAWANG",
   "id": 7313142010,
   "organisasi": "Forum Rakyat Bersatu (FRB) Keera.",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara XIV",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 120.350349,
   "lat": -3.808083745
 },
 {
   "provinsi": "SULAWESI TENGAH",
   "kabkot": "BANGGAI",
   "kecamatan": "BUNTA",
   "desa": "BOHOTOKONG",
   "id": 7201022015,
   "organisasi": "Ortabun",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Anugerah Saritama Abadi",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 122.1611705,
   "lat": -0.876763224
 },
 {
   "provinsi": "SULAWESI TENGAH",
   "kabkot": "POSO",
   "kecamatan": "PAMONA TENGGARA",
   "desa": "BARATI",
   "id": 7202262009,
   "organisasi": "Solidaritas Perempuan Sintuwu Raya Poso",
   "penggunaan": "Perkebunan Warga & Peternakan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Sawit Jaya Abadi",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 120.8165832,
   "lat": -2.067556982
 },
 {
   "provinsi": "SULAWESI TENGAH",
   "kabkot": "SIGI",
   "kecamatan": "KINOVARO",
   "desa": "BOLOBIA",
   "id": 7210132005,
   "organisasi": "Serikat Tani Bolobia",
   "penggunaan": "perkebunan, pemukiman, pesawahan, peternakan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Balai Konservasi Sumber Daya Alam",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Lindung",
   "tahapan": "Identifikasi",
   "long": 119.7961443,
   "lat": -0.984468322
 },
 {
   "provinsi": "SULAWESI TENGAH",
   "kabkot": "SIGI",
   "kecamatan": "PALOLO",
   "desa": "TONGOA",
   "id": 7210022016,
   "organisasi": "Forum Petani Merdeka (FPM)",
   "penggunaan": "PERKEBUNAN DAN PETERNAKAN",
   "status_tan": "Tanah Hak Milik Transmigrasi",
   "pihak_terl": "Balai Konservasi Sumber Daya Alam",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Lindung",
   "tahapan": "Redistribusi",
   "long": 120.1849274,
   "lat": -1.224195146
 },
 {
   "provinsi": "SULAWESI TENGAH",
   "kabkot": "TOLITOLI",
   "kecamatan": "LAMPASIO",
   "desa": "LAMPASIO",
   "id": 7204062004,
   "organisasi": "Forum Petani Cengkeh",
   "penggunaan": "pesawahan",
   "status_tan": "Tanah Hak Milik",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Citra Mulia Perkasa",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 120.774096,
   "lat": 0.884557741
 },
 {
   "provinsi": "SULAWESI TENGGARA",
   "kabkot": "KOLAKA",
   "kecamatan": "BAULA",
   "desa": "PUULEMO",
   "id": 7401122004,
   "organisasi": "Forsda Kolaka",
   "penggunaan": "perkebunan",
   "status_tan": "Hutan Lindung",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "(blank)",
   "tipologi": "Penetapan Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 121.7365686,
   "lat": -4.158084104
 },
 {
   "provinsi": "SULAWESI UTARA",
   "kabkot": "BOLAANG MONGONDOW",
   "kecamatan": "LOLAK",
   "desa": "LOLAK II",
   "id": 7101122018,
   "organisasi": "Serikat Petani Minahasa (SPM)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Mongondow Indah",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 124.0671046,
   "lat": 0.831696164
 },
 {
   "provinsi": "SULAWESI UTARA",
   "kabkot": "MINAHASA SELATAN",
   "kecamatan": "TENGA",
   "desa": "SAPA",
   "id": 7105092010,
   "organisasi": "Serikat Petani Minahasa Selatan (SPMS)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Batu Kapal",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pemetaan",
   "long": 124.3967973,
   "lat": 1.160029826
 },
 {
   "provinsi": "SULAWESI UTARA",
   "kabkot": "MINAHASA TENGGARA",
   "kecamatan": "BELANG",
   "desa": "MANGKIT",
   "id": 7107032001,
   "organisasi": "Serikat Petani Minahasa Tenggara (SPMT)",
   "penggunaan": "pertanian, pemukiman",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Asiatik",
   "tipologi": "HGU Habis Perkebunan Swasta",
   "tahapan": "Pengorganisasian",
   "long": 124.7665969,
   "lat": 0.931606224
 },
 {
   "provinsi": "SUMATERA BARAT",
   "kabkot": "PASAMAN BARAT",
   "kecamatan": "PASAMAN",
   "desa": "AIA GADANG",
   "id": 1312032006,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "perkebunan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Anam Koto",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 99.78902329,
   "lat": 0.15802376
 },
 {
   "provinsi": "SUMATERA SELATAN",
   "kabkot": "MUSI RAWAS",
   "kecamatan": "MUARA LAKITAN",
   "desa": "SEMANGUS",
   "id": 1605022002,
   "organisasi": "AMAN Sumsel, Walhi Sumsel",
   "penggunaan": "perkebunan",
   "status_tan": "Tanah Hak Milik Transmigrasi",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Musi Hutan Persada",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 103.5772009,
   "lat": -3.297116022
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "DELI SERDANG",
   "kecamatan": "BATANG KUIS",
   "desa": "MESJID",
   "id": 1207272010,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 98.83480558,
   "lat": 3.660622609
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "DELI SERDANG",
   "kecamatan": "BATANG KUIS",
   "desa": "SUGIHARJO",
   "id": 1207272011,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 98.81486842,
   "lat": 3.660631136
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "DELI SERDANG",
   "kecamatan": "BERINGIN",
   "desa": "BERINGIN",
   "id": 1207332007,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 98.87715951,
   "lat": 3.639411712
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "DELI SERDANG",
   "kecamatan": "HAMPARAN PERAK",
   "desa": "KLAMBIR",
   "id": 1207242007,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 98.57493592,
   "lat": 3.748934188
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "DELI SERDANG",
   "kecamatan": "PATUMBAK",
   "desa": "SIGARA GARA",
   "id": 1207212005,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 98.73641709,
   "lat": 3.518268128
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "HUMBANG HASUNDUTAN",
   "kecamatan": "POLLUNG",
   "desa": "POLLUNG",
   "id": 1216022003,
   "organisasi": "Kelompok Studi dan Pengembangan Prakarsa Masyarakat (KSPPM)",
   "penggunaan": "Perkampungan, perladangan, dan persawahan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Toba Pulp Lestari",
   "tipologi": "Penunjukan Kawasan Hutan",
   "tahapan": "Pemetaan",
   "long": 98.7279589,
   "lat": 2.340479522
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SECANGGANG",
   "desa": "CINTA RAJA",
   "id": 1205092003,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 98.49222171,
   "lat": 3.838672232
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SECANGGANG",
   "desa": "KARANG GADING",
   "id": 1205092010,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 98.56551618,
   "lat": 3.839087526
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SECANGGANG",
   "desa": "KWALA BESAR",
   "id": 1205092014,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 98.62590372,
   "lat": 3.897256715
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SECANGGANG",
   "desa": "SECANGGANG",
   "id": 1205092008,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 98.53875616,
   "lat": 3.856170508
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SECANGGANG",
   "desa": "TELUK",
   "id": 1205092002,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 98.51686076,
   "lat": 3.809489034
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SELESAI",
   "desa": "MANCANG",
   "id": 1205062011,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 98.42139497,
   "lat": 3.647829544
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "SELESAI",
   "desa": "SEI LIMBAT",
   "id": 1205062002,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 98.43184053,
   "lat": 3.624163811
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "WAMPU",
   "desa": "GOHOR LAMA",
   "id": 1205082002,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pengorganisasian",
   "long": 98.3860412,
   "lat": 3.759895226
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "LANGKAT",
   "kecamatan": "WAMPU",
   "desa": "PERTUMBUKAN",
   "id": 1205082010,
   "organisasi": "Badan Perjuangan Rakyat Penungu Indonesia (BPRPI)",
   "penggunaan": "Pertanian, Perkebunan dan Pemukiman",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Pemetaan",
   "long": 98.39413256,
   "lat": 3.719099707
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "MANDAILING NATAL",
   "kecamatan": "NATAL",
   "desa": "BINTUAS",
   "id": 1213162002,
   "organisasi": "Konsorsium Pembaruan Agraria",
   "penggunaan": "Pertanian",
   "status_tan": "Tanah HGU Aktif",
   "pihak_terl": "Perusahaan Perkebunan Swasta",
   "perusahaan": "PT. Rimba Mujur Mahkota\n PT. Dinamika Inti Sentosa",
   "tipologi": "HGU Aktif Perkebunan Swasta",
   "tahapan": "Identifikasi",
   "long": 99.07916978,
   "lat": 0.698225032
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "SAMOSIR",
   "kecamatan": "PALIPI",
   "desa": "PALIPI",
   "id": 1217042004,
   "organisasi": "Kelompok Studi dan Pengembangan Prakarsa Masyarakat (KSPPM)",
   "penggunaan": "perkampungan dan perladangan",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Perusahaan Kehutanan Swasta",
   "perusahaan": "PT. Toba Pulp Lestari",
   "tipologi": "Konsesi Hutan Produksi",
   "tahapan": "Pemetaan",
   "long": 98.79683261,
   "lat": 2.510862525
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "SAMOSIR",
   "kecamatan": "RONGGUR NIHUTA",
   "desa": "SIJAMBUR",
   "id": 1217072008,
   "organisasi": "Kelompok Studi dan Pengembangan Prakarsa Masyarakat (KSPPM)",
   "penggunaan": "perkampungan, perladangan, persawahan, dan tempat penggembalaan ternak",
   "status_tan": "Tanah Adat",
   "pihak_terl": "Kementerian Lingkungan Hidup dan Kehutanan",
   "perusahaan": "Balai Konservasi Sumber Daya Alam",
   "tipologi": "Penetapan Hutan Lindung",
   "tahapan": "Redistribusi",
   "long": 98.7923751,
   "lat": 2.624731675
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "SERDANG BEDAGAI",
   "kecamatan": "PEGAJAHAN",
   "desa": "BINGKAT",
   "id": 1218142002,
   "organisasi": "Serikat Petani Serdang Bedagai (SPSB)",
   "penggunaan": "pemukiman dan lahan tanaman keras dan palawija",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara II",
   "tipologi": "HGU Habis Perkebunan Negara",
   "tahapan": "Identifikasi",
   "long": 98.95619625,
   "lat": 3.480825607
 },
 {
   "provinsi": "SUMATERA UTARA",
   "kabkot": "SIMALUNGUN",
   "kecamatan": "SIANTAR",
   "desa": "SILAMPUYANG",
   "id": 1208012001,
   "organisasi": "FUTASI",
   "penggunaan": "perkebunan",
   "status_tan": "Tanah Terlantar Bekas HGU",
   "pihak_terl": "Perusahaan Perkebunan Negara",
   "perusahaan": "PT. Perkebunan Nusantara IV",
   "tipologi": "HGU Aktif Perkebunan Negara",
   "tahapan": "Redistribusi",
   "long": 99.07068314,
   "lat": 2.906237766
 }
]